add functionality to post comments
jayascript1/NC-News pull request #5
Opened 2023-03-30 12:23 UTC by jayascript1

2023-03-30 12:47 UTC, callumu21 requested changes
Good start! Just missing a few extra tests, which I've included in a comment below.

I would also look at refactoring your error handling. Currently, a lot is taking place in the controller, when it doesn't need to. Try to use PSQL thrown errors as much as possible, as it will save you time and logic down the line 👍 

Once you've made these changes, please resend this PR for approval 😄

2023-03-30 12:47 UTC, callumu21 commented on __tests__/app.test.js
> +      expect(postedComment.author).toEqual(newComment.username);
Your posted comment should also have some extra properties (e.g. votes, created_at, comment_id). You also want to make sure that these are included

2023-03-30 12:47 UTC, callumu21 commented on __tests__/app.test.js
> +  it('returns a 400 error when missing required properties', () => {
You may want to make this more precise (e.g. when username is missing)

2023-03-30 12:47 UTC, callumu21 commented on __tests__/app.test.js
> +});
Just missing a few extra tests:

1. Invalid article_id
2. Username is included on the POST request but the username isn't in our database
3. POST body contains username and body but has extra properties

2023-03-30 12:47 UTC, callumu21 commented on controllers/postComment.js
> +  if (isNaN(article_id)) {
PSQL will handle this error for us automatically, so this extra logic isn't required.

2023-03-30 12:47 UTC, callumu21 commented on controllers/postComment.js
> +          comment,
We only need to send back the comment here, rather than the message. We can tell it was successfully added by the status code

2023-03-30 12:47 UTC, callumu21 commented on controllers/postComment.js
> +        const err = new Error("Not found");
This logic should be handled in the model. You know if you get back an empty array that the article_id was not in the database, so you can use Promise.reject() to throw an error

2023-03-30 14:38 UTC, Pipe-Smoking-Rabbit requested changes
Some good changes have been made but it seems to still be missing some key tests that were proposed in the last review; 
- What if there are extra properties in the request, will your API be able to ignore unnecessary properties and still successfully complete the post ✉️ 
- What if the username provided does not match any username in the database ? For example, `username: "new-number-who-dis"`
- What if the article_id is not a number ?

2023-03-31 09:50 UTC, johnhutcheon requested changes
Hi Jay. You're nearly there with this! In Mitch's last review he said...

- What if there are extra properties in the request, will your API be able to ignore unnecessary properties and still successfully complete the post ✉️

For this, we're just basically looking for another 201 test which will ignore any extra properties. For example, if we sent our object to contain body, username and something else random. Hope this makes sense, but give us a shout if not. 🙂

2023-03-31 10:34 UTC, pippaamy reviewed
Good job, we just have one more test to write. If you pop in a 201 test in your test suite. We can give it an object of { username: "username", body: "something" , ignoredProp: "something ignored" } just so we see that it only pays attention to the username and body :)

2023-03-31 10:41 UTC, pippaamy approved these changes
Fab, all good!

2023-03-31 10:43 UTC, merged